# Generated by Django 2.0 on 2018-02-23 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180221_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
        migrations.AddField(
            model_name='member',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
